### ISSUE TITLE
Invalid client_id parameter

### ISSUE THREAD

**Issue by ADWadmin** [outline/outline#1091]
Hello!
I deployed Outline on my own physical server, for my company.
And ran into the following bug:

It is not possible to integrate with Slack (for the `/outline` commands to work):
When clicking on the `Add to Slack` button on the page „https://my domain.com/settings/integrations/slack“ an error occurs: „Invalid client_id parameter“, and indeed the following is entered in the URL bar of the browser: 
„https: //slack.com/oauth/authorize?client_id=**undefined**&scope=commands%20links%3Aread%20links%3Awrite&redirect_uri=**undefined**%2Fauth%2Fslack.commands&state=908ac7e0-facf-43d4-946a-bbacfdb166a2&tracked=1“

How to integrate outline into Slack for the "/ outline" commands?

> Used configuration:
> Ubuntu 18.04.3 LTS
> Node.js v13.2.0
> pm2 v4.1.2
> NPM v6.13.1
> PostgresSQL v10.10
> Redis server v4.0.9
> Minio 2019-10-12T01:39:57Z
> Apache/2.4.29 (reverse proxy SSL)
> Slack

**Comment by tommoor** [comment]
If these values are `undefined` then they must not be correctly set as environment variables:

https://github.com/outline/outline#production

**Comment by ADWadmin** [comment]
That is the whole point!
All the `SLACK_` variables in the `.env` file are specified correctly.

If I intentionally delete or specify incorrect values `SLACK_KEY` or `SLACK_SECRET` then the ability to log in to Outline will disappear.
When I click `Sign in with Slack` on the login page, the correct request is sent to the address bar of the browser:
https:// slack.com/oauth/authorize?client_id=**76XXXXXXX.XXXXXXX57**&scope=identity.email%20identity.basic%20identity.avatar%20identity.team&redirect_uri=https%3A%2F%2Fmy-domain.com%2Fauth%2Fslack.callback&state=3kb1a9&tracked=1

**Comment by tommoor** [comment]
Gotcha, thanks for the clarification. Based on that, I suspect this is because you are defining the environment variables in an `.env` file – in a production environment you should export them as real environment variables.

**Comment by ADWadmin** [comment]
@tommoor I apologize for the long silence.
I did not quite understand you, but I tried to run Outline with the variables:

`NODE_ENV=production REDIRECT_URL=https://my-domain.com CLIENT_ID=76XXXXXXX.XXXXXXX58 pm2 start index.js --name outline`

If you request a list of process variables:

> $ pm2 id outline
> [ 0 ]
> $ pm2 env 0
> 
> node_version: 13.3.0
> version: 0.18.0
> unique_id: 61cffc60-2c0d-4746-8fcb-23e480f678e7
> PM2_HOME: /home/username/.pm2
> NODE_ENV: production
> **REDIRECT_URL: https://my-domain.com
> CLIENT_ID: 76XXXXXXX.XXXXXXX58**
> LS_COLORS: rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*
> ...blah blah blah…

It did not help.

After, I tried to register these variables in `/etc/profile`, `/etc/bash.bashrc` and `/etc/environment`.

Now the variables are accessible to everyone and everywhere:

> \$ echo $REDIRECT_URL
> https://my-domain.com
> \$ sudo -s
> \# echo $REDIRECT_URL
> https://my-domain.com


This also did not produce any effect.
Are you sure the problem is not on your side?

**Comment by tommoor** [comment]
The environment variables you mention don't exist. It's `SLACK_KEY` and `URL`.

https://github.com/outline/outline/blob/master/.env.sample#L12-L26

**Comment by ADWadmin** [comment]
@tommoor  Bro, I know that =)
But just in case, I registered absolutely **all** the variables:

> NODE_ENV=production
> URL=https://my-domain.com
> REDIRECT_URL=https://my-domain.com
> REDIRECT_URI=https://my-domain.com
> SLACK_KEY=76XXXXXXX.XXXXXXX58
> CLIENT_ID=76XXXXXXX.XXXXXXX58
> SLACK_VERIFICATION_TOKEN=8vXXXXXXXXXXXXYR
> SLACK_APP_ID=AXXXXXJ

It does not help.

I will also remind you that when I click `Sign in with Slack` on the login page, the parameters `redirect_uri` and `client_id` are transferred successfully. (see: https://github.com/outline/outline/issues/1091#issuecomment-561522657)
It turns out that during authorization these variables are successfully determined, but when trying to integrate not.
(When I click `Sign in with Slack` button on the login page, `redirect_uri` and `client_id` correctly determined.
When i click `Add to Slack` button on the settings page, `redirect_uri` and `client_id` undefined.)

P.S.
By the way, I noticed that in my first post, in the quote URL:

> „https: //slack.com/oauth/authorize?client_id=undefined&scope=commands%20links%3Aread%20links%3Awrite&redirect_uri=undefined%2Fauth%2Fslack.commands&state=908ac7e0-facf-43d4-946a-bbacfdb166a2&tracked=1“

It is written, `redirect_uri`, not `redirect_url`.

**Comment by ADWadmin** [comment]
The question is still relevant. =(

Am I alone faced with a similar error?
@tommoor Can you tell me how to fix this?

**Comment by tommoor** [comment]
@ADWadmin you do see to be the only one with the issue. The difference with the `client_id` on the integration page is that it's compiled into the frontend javascript bundle – this means that the `env` variable must be set when the webpack compilation happens, perhaps this is where your setup differs?

It makes me wonder if we could change this to have a simple redirect on the server to avoid bundling the key in the clientside entirely. 🤔

**Comment by ADWadmin** [comment]
It is decided:

I redeployed, but this time I used `Node.js v12.14.1`, not `Node.js v13.2.0`.
I think this requires additional testing.

**Comment by zenopopovici** [comment]
I have the same issue...

**Comment by zenopopovici** [comment]
Fixed: please make sure you have your .env set and run `yarn build:webpack`.

**Comment by todor-ops** [comment]
I have a problem with same output. Accidentally deleted slack app, create another one, updated .env file, run yarn build:webpack in Outline container, but no success. Now I have: Invalid client_id parameter in browser, and old client ID in URL when try to login in Outline: https://slack.com/oauth/authorize?client_id=460658912391.879928214421&scope=identity.email%20identity.basic%20identity.avatar%20identity.team&redirect_uri=http%3A%2F%28888888888%2Fauth%2Fslack.callback&state=sse4oni&tracked=1

**Comment by tommoor** [comment]
This thread is quite old, there is no longer a need to run `build:webpack`, environment variables are sent from the server at runtime. If you're running an uptodate version and the client_id is old then the environment variables must not be updated correctly.

**Comment by todor-ops** [comment]
printenv from outline docker container show new slack key and secret in .env file

**Comment by mike-lloyd03** [comment]
I'm still having this problem. Using docker compose and the default `.env` file, `SLACK_CLIENT_ID` was set to `get_a_key_from_slack` on first run. I've since updated it to the correct key by updating the `.env` file and redeploying the Compose stack.

Running `docker compose exec outline env` reveals that the `SLACK_CLIENT_ID` is correctly being set in the environment. But when I try to connect to Slack, it's still passing `client_id=get_a_key_from_slack` in the URL parameters. It seems like this variable isn't being sourced at runtime as expected.
