### ISSUE TITLE
Slack Integration + Google Auth

### ISSUE THREAD

**Issue by blainsmith** [outline/outline#730]
After connected from the Settings -> Integrations page in Outline the "Add to Slack" button is still grey. Then when i try the Slack command `/outline <keyword>` I get the following response in Slack.

*/outline pull request* failed with the error "400_client_error"

I haven't been able to debug it yet, but perhaps there was an issue with the initial integration connection. Under the "Configure apps" section in Slack the integration looks fine though.

**Comment by tommoor** [comment]
Thanks for the report @blainsmith – would you mind trying again? This should be addressed now.

**Comment by blainsmith** [comment]
Well I got past the original error, but now I think there is an issue where I am logged into Slack with a different email than the one with Outline since I used Google to log into Outline and not Slack.

![screenshot from 2018-08-02 10-30-25](https://user-images.githubusercontent.com/483829/43590964-4b8a2daa-9640-11e8-98e7-64ddd67fe859.png)

**Comment by tommoor** [comment]
Ah interesting, that scenario might have been overlooked. I'll take a dive into that later – thanks for your patience 🙏

**Comment by tommoor** [comment]
@blainsmith reproduced, fixed and tested. Thanks for reporting!

**Comment by coronadouglass** [comment]
I still have the same error,  I have connected with Slack and Google account, but I have two different accounts in getoutline.com.  Both are authorized with Slack, but just one responds correctly with /outline, Slack signed. If I delete getouline account (Slack), I get an error "400_client_error" I tried to delete both getoutline accounts , but these accounts aren't deleted.  
On slack if I run /outline <keyword>, the account that responds is that I signed with Slack. Also, with one account I have admin permissions (Google) and I don't have admin permissions with Slack account.

**Comment by tommoor** [comment]
@coronadouglass it sounds like you're getting signin and the slack integration mixed up, to connect the Slack integration go to:

https://www.getoutline.com/settings/integrations/slack

You should choose either Google or Slack for signin.

**Comment by coronadouglass** [comment]
I got a message Integration failed to delete, when I try  The problem is that we use Google to log onto Slack. So I think I could use Google and Slack at the same time, but I created two accounts. Is it possible to delete those account and start over again ?  Any email to send you which accounts I want to delete ?

**Comment by coronadouglass** [comment]
I can't integrate Slack when I sign with a Google account, even if I authorize Slack. That gives me 400_client_error
