### ISSUE TITLE
Unable to import Markdown zip

### ISSUE THREAD

**Issue by muuvmuuv** [outline/outline#8879]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This is not related to configuring Outline

- [x] The issue is not related to self-hosting config

### Current Behavior

Importing the attached zip results in the image beeing a binary-like markdown page, no image upload and the actual markdown page to have a broken image.

### Expected Behavior

As from these two issues I changed any path to absolute paths and also tried some other modifications #7512 #6273

### Steps To Reproduce

1. Upload zip using Markdown importer

### Environment

```markdown
- Outline: 0.82.0
- Browser: Safari
```

### Anything else?

[test.zip](https://github.com/user-attachments/files/19600775/test.zip)

**Comment by muuvmuuv** [comment]
Also exported a sample page which I can also not import again, this time this zip contains Outline markdown code and structure. 

[Test-export.markdown.zip](https://github.com/user-attachments/files/19600831/Test-export.markdown.zip)

**Comment by tommoor** [comment]
I'm unable to reproduce on `main`, this issue must have been addressed since 82

**Comment by muuvmuuv** [comment]
I am, using test-zip with the current latest release 0.83.0 I see this after importing using "Import Markdown" and no image in the document.

![Image](https://github.com/user-attachments/assets/4d0dd28e-6571-4324-94e2-0b9ebf22b722)

**Comment by muuvmuuv** [comment]
We aren't using a S3, so local filestorage:
```ini
FILE_STORAGE=local
FILE_STORAGE_LOCAL_ROOT_DIR=/var/lib/outline/data
```
Here is a part of debug log:
```

**Comment by muuvmuuv** [comment]
Hey, does the logs show something to you? I could provide more if you tell me where to search for. We are still unable to do mass-imports... and zip's created by Outline also fail so it must be something with our installation/configuration I guess.
